services:
  - type: web
    name: gesture-backend
    env: python
    repo: https://github.com/your-username/GestureGuy
    branch: master
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host=0.0.0.0 --port=10000
    plan: free
